### ISSUE TITLE
Race condition on ringbuffer access 

### ISSUE THREAD

**Issue by gnumpi** [esphome/home-assistant-voice-pe#221]
I found a race condition issue in the Nabu MediaPlayer implementation.

Specifically, the media_ring_buffer_ (audio mixer) is accessed concurrently by two tasks: mixer_task and resampler_task, which may run on different ESP cores. While the xStreamBuffer is protected using taskENTER_CRITICAL, in my understanding this protection is ineffective when the two tasks run on separate cores, as taskENTER_CRITICAL only disables interrupts to prevent task switching.

This race condition occasionally leads to an xTaskNotify assertion failure, causing a system reboot during music playback.

To resolve the issue, I pinned both tasks (mixer_task and resampler_task) to the same core using xTaskCreateStaticPinnedToCore. This change seems to mitigate the problem.

**Comment by kahrendt** [comment]
Thanks for raising this issue! I've been chasing this bug for awhile and came up with a different solution: https://github.com/esphome/esphome/pull/7973
I implemented the ring buffer class using the xRingbuffer class instead of stream buffers, which fixes the race condition without requiring anything to be pinned to a core (which is good, as the speaker component now also uses ring buffers, so we would need to pin essentially every single audio task using a ring buffer to a single core to avoid it 100% of the time).
